name: Deploy to Aliyun OSS

on:
  push:
    branches:
      - dev # 或者你的主分支名

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ossutil
        uses: manyuanrong/ossutil-action@master
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: Deploy to Aliyun OSS
        run: ossutil cp -rf ./ oss://orcalab-docs/